
package eu.geomodel.schema.ws.pvplanner;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PvPlannerPort", targetNamespace = "http://geomodel.eu/schema/ws/pvplanner")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PvPlannerPort {


    /**
     * 
     * @param calculateRequest
     * @return
     *     returns eu.geomodel.schema.ws.pvplanner.CalculateResponse
     */
    @WebMethod
    @WebResult(name = "calculateResponse", targetNamespace = "http://geomodel.eu/schema/ws/pvplanner", partName = "calculateResponse")
    public CalculateResponse calculate(
        @WebParam(name = "calculateRequest", targetNamespace = "http://geomodel.eu/schema/ws/pvplanner", partName = "calculateRequest")
        CalculateRequest calculateRequest);

}
