
package eu.geomodel.schema.ws.pvplanner;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PvPlannerPortService", targetNamespace = "http://geomodel.eu/schema/ws/pvplanner", wsdlLocation = "file:C:\\Users\\marcelo.araya-gomez\\eclipse-workspace-vigorsolar\\solargis-test\\src\\main\\resources\\pvPlannerWebService.wsdl")
public class PvPlannerPortService
    extends Service
{

    private final static URL PVPLANNERPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PVPLANNERPORTSERVICE_EXCEPTION;
    private final static QName PVPLANNERPORTSERVICE_QNAME = new QName("http://geomodel.eu/schema/ws/pvplanner", "PvPlannerPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:C:\\Users\\marcelo.araya-gomez\\eclipse-workspace-vigorsolar\\solargis-test\\src\\main\\resources\\pvPlannerWebService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PVPLANNERPORTSERVICE_WSDL_LOCATION = url;
        PVPLANNERPORTSERVICE_EXCEPTION = e;
    }

    public PvPlannerPortService() {
        super(__getWsdlLocation(), PVPLANNERPORTSERVICE_QNAME);
    }

    public PvPlannerPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PVPLANNERPORTSERVICE_QNAME, features);
    }

    public PvPlannerPortService(URL wsdlLocation) {
        super(wsdlLocation, PVPLANNERPORTSERVICE_QNAME);
    }

    public PvPlannerPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PVPLANNERPORTSERVICE_QNAME, features);
    }

    public PvPlannerPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PvPlannerPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PvPlannerPort
     */
    @WebEndpoint(name = "PvPlannerPortSoap11")
    public PvPlannerPort getPvPlannerPortSoap11() {
        return super.getPort(new QName("http://geomodel.eu/schema/ws/pvplanner", "PvPlannerPortSoap11"), PvPlannerPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PvPlannerPort
     */
    @WebEndpoint(name = "PvPlannerPortSoap11")
    public PvPlannerPort getPvPlannerPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://geomodel.eu/schema/ws/pvplanner", "PvPlannerPortSoap11"), PvPlannerPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PVPLANNERPORTSERVICE_EXCEPTION!= null) {
            throw PVPLANNERPORTSERVICE_EXCEPTION;
        }
        return PVPLANNERPORTSERVICE_WSDL_LOCATION;
    }

}
